# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d31f036db56d21d76b53a4ec4504caa43df0c4fc74358b120ee02be54663453cebc39734d81969ccd5366c04733fa7e6528b4eaf6a8a98a293129c45b4fe48e0

test:
  secret_key_base: ef1e168b0096da8f9a3f361e3e0f21b678b36e9e9514f8225026ded8f036053dd7934dc4d86470c47fbeb9c0e319a1d3950a1621c249f8b23f4a7089cdf74bd6

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
